/**
 * Reads .env in the project root and writes groq-config.gen.js for the extension.
 * Run: node scripts/sync-env.js
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const envPath = path.join(root, ".env");
const outPath = path.join(root, "groq-config.gen.js");

function parseEnv(text) {
  const out = {};
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

if (!fs.existsSync(envPath)) {
  console.error("Missing .env — copy .env.example to .env and set GROQ_API_KEY.");
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, "utf8"));
const key = env.GROQ_API_KEY || "";
if (!key) {
  console.error(".env must define GROQ_API_KEY=...");
  process.exit(1);
}

const body = `// Generated by scripts/sync-env.js — do not edit or commit.\nwindow.__GROQ_API_KEY__=${JSON.stringify(
  key
)};\n`;
fs.writeFileSync(outPath, body, "utf8");
console.log("Wrote groq-config.gen.js from .env");
